name: A workflow for building Buildroot artifacts
on: push

jobs:
  build:
    name: Build system
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nerves-project/nerves_system_br:1.28.2
      options: --user root
    env:
      ELIXIR_VERSION: 1.17.2-otp-27
      NERVES_BOOTSTRAP_VERSION: 1.13.0
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup cache
        id: cache-buildroot-downloads
        uses: actions/cache@v3
        with:
          path: _build/dl
          key: buildroot-${{ hashFiles('mix.lock') }}

      - name: Setup elixir
        run: |
          wget https://repo.hex.pm/builds/elixir/v$ELIXIR_VERSION.zip
          unzip -d /usr/local/elixir v$ELIXIR_VERSION.zip
          echo "/usr/local/elixir/bin" >> $GITHUB_PATH

      - name: Install nerves_bootstrap
        run: |
          sudo -u nerves mix local.hex --force
          sudo -u nerves mix local.rebar --force
          sudo -u nerves mix archive.install hex nerves_bootstrap $NERVES_BOOTSTRAP_VERSION --force

      - name: Create artifact dir 
        run: |
          sudo chown -R nerves:nerves $GITHUB_WORKSPACE
          sudo -u nerves mkdir -p deploy/system/artifacts

      - name: Build
        run: |
          sudo -u nerves mix deps.get
          sudo -u nerves mix nerves.artifact --path deploy/system/artifacts

      - name: Upload Artifacts and Create Release
        if: contains(github.ref, 'tags')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deploy/system/artifacts/*
          file_glob: true
          tag: ${{ github.ref }}


